export const azureServices = {
    Backend: [
      {
        title: 'Azure Functions',
        desc: 'Azure Functions is a serverless compute service that enables you to run event-triggered code without having to explicitly provision or manage infrastructure.',
        id: 'service_function',
      },
      {
        title: 'Azure API Management',
        desc: 'Azure API Management is a turnkey solution for publishing APIs to external and internal customers.',
        id: 'service_api_gateway',
      },
      {
        title: 'Azure SQL Database',
        desc: 'Azure SQL Database is a fully managed relational database with built-in intelligence.',
        id: 'service_db',
      },
      {
        title: 'Azure Blob Storage',
        desc: 'Azure Blob Storage is a service for storing large amounts of unstructured data.',
        id: 'service_blob_storage',
      },
      {
        title: 'Azure Cosmos DB',
        desc: 'Azure Cosmos DB is a globally distributed, multi-model database service.',
        id: 'service_cosmos_db',
      },
    ],
    Frontend: {
      WebApp: [
        {
          title: 'Azure Static Web Apps',
          desc: 'Azure Static Web Apps is a service that automatically builds and deploys full stack web apps to Azure from a code repository.',
          id: 'service_web',
        },
        {
          title: 'Azure API Management',
          desc: 'Azure API Management is a turnkey solution for publishing APIs to external and internal customers.',
          id: 'service_web_api',
        },
        {
          title: 'Azure SQL Database',
          desc: 'Azure SQL Database is a fully managed relational database with built-in intelligence.',
          id: 'service_web_db',
        },
      ],
      MobileApp: [
        {
          title: 'Azure Static Web Apps',
          desc: 'Azure Static Web Apps is a service that automatically builds and deploys full stack web apps to Azure from a code repository.',
          id: 'service_mobile',
        },
        {
          title: 'Azure API Management',
          desc: 'Azure API Management is a turnkey solution for publishing APIs to external and internal customers.',
          id: 'service_mobile_api',
        },
        {
          title: 'Azure SQL Database',
          desc: 'Azure SQL Database is a fully managed relational database with built-in intelligence.',
          id: 'service_mobile_db',
        },
      ],
    },
    Monitoring: [
      {
        title: 'Azure Monitor',
        desc: 'Azure Monitor is a full stack monitoring service that provides a complete set of features to monitor your applications, infrastructure, and network.',
        id: 'service_monitor',
      },
      {
        title: 'Azure Log Analytics',
        desc: 'Azure Log Analytics is a service in Azure Monitor that helps you collect and analyze data generated by resources in your cloud and on-premises environments.',
        id: 'service_log',
      },
    ],
  };