import React from 'react';
import { Box, Button, Typography } from '@mui/material';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { materialDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import ExpandableSection from './ExpandableSection';

interface CodeSection {
    title: string;
    code: string;
}

interface CodeGenProps {
    sections: CodeSection[];
}

const CodeGen: React.FC<CodeGenProps> = ({ }) => {

    const sections = [
        {
            title: 'Section 1: Component Definition',
            code: `
      import React from 'react';
      
      const MyComponent: React.FC = () => {
        return <div>Hello, World!</div>;
      };
      
      export default MyComponent;
          `,
        },
        {
            title: 'Section 2: Usage Example',
            code: `
      import React from 'react';
      import MyComponent from './MyComponent';
      
      const App: React.FC = () => {
        return (
          <div>
            <MyComponent />
          </div>
        );
      };
      
      export default App;
          `,
        },
    ];

    const azureServices = {
        Backend: [
            {
                title: 'Azure Functions',
                desc: 'Azure Functions is a serverless compute service that enables you to run event-triggered code without having to explicitly provision or manage infrastructure.',
                id: 'service_function',
            },
            {
                title: 'Azure API Management',
                desc: 'Azure API Management is a turnkey solution for publishing APIs to external and internal customers.',
                id: 'service_api_gateway',
            },
            {
                title: 'Azure SQL Database',
                desc: 'Azure SQL Database is a fully managed relational database with built-in intelligence.',
                id: 'service_db',
            },
            {
                title: 'Azure Blob Storage',
                desc: 'Azure Blob Storage is a service for storing large amounts of unstructured data.',
                id: 'service_blob_storage',
            },
            {
                title: 'Azure Cosmos DB',
                desc: 'Azure Cosmos DB is a globally distributed, multi-model database service.',
                id: 'service_cosmos_db',
            },
        ],
        Frontend: {
            WebApp: [
                {
                    title: 'Azure Static Web Apps',
                    desc: 'Azure Static Web Apps is a service that automatically builds and deploys full stack web apps to Azure from a code repository.',
                    id: 'service_web',
                },
                {
                    title: 'Azure API Management',
                    desc: 'Azure API Management is a turnkey solution for publishing APIs to external and internal customers.',
                    id: 'service_web_api',
                },
                {
                    title: 'Azure SQL Database',
                    desc: 'Azure SQL Database is a fully managed relational database with built-in intelligence.',
                    id: 'service_web_db',
                },
            ],
            MobileApp: [
                {
                    title: 'Azure Static Web Apps',
                    desc: 'Azure Static Web Apps is a service that automatically builds and deploys full stack web apps to Azure from a code repository.',
                    id: 'service_mobile',
                },
                {
                    title: 'Azure API Management',
                    desc: 'Azure API Management is a turnkey solution for publishing APIs to external and internal customers.',
                    id: 'service_mobile_api',
                },
                {
                    title: 'Azure SQL Database',
                    desc: 'Azure SQL Database is a fully managed relational database with built-in intelligence.',
                    id: 'service_mobile_db',
                },
            ],
        },
        Monitoring: [
            {
                title: 'Azure Monitor',
                desc: 'Azure Monitor is a full stack monitoring service that provides a complete set of features to monitor your applications, infrastructure, and network.',
                id: 'service_monitor',
            },
            {
                title: 'Azure Log Analytics',
                desc: 'Azure Log Analytics is a service in Azure Monitor that helps you collect and analyze data generated by resources in your cloud and on-premises environments.',
                id: 'service_log',
            },
        ],
    };

    return (
        <Box sx={{ padding: 2 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
            <Typography variant="h3">Prototype Code Gen tool</Typography>
            <Box>
            
              <Button variant="contained" color="primary" sx={{ mr: 1 }}>
                Generate Learning Roadmap
              </Button>
              <Button variant="contained" color="secondary">
                Generate Code for prototype
              </Button>
            </Box>
          </Box>
            <ExpandableSection></ExpandableSection>
            {sections.map((section, index) => (
                <Box key={index} sx={{ marginBottom: 4 }}>
                    <Typography variant="h6" sx={{ marginBottom: 1 }}>
                        {section.title}
                    </Typography>
                    <SyntaxHighlighter language="typescript" style={materialDark}>
                        {section.code}
                    </SyntaxHighlighter>
                </Box>
            ))}
        </Box>
    );
};

export default CodeGen;
